# Shared by the toolchain files. A toolchain file runs again for every try_compile project, where the cache of the
# main project is not visible: the DAGOR_* values it needs reach those projects through
# CMAKE_TRY_COMPILE_PLATFORM_VARIABLES, so each value is resolved once by the first run and reused afterwards.
cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH _dagor_cmake_dir)
include("${_dagor_cmake_dir}/DagorHost.cmake")
include("${_dagor_cmake_dir}/DagorFetch.cmake")
unset(_dagor_cmake_dir)

if(NOT DAGOR_ARCH)
  set(DAGOR_ARCH "${DAGOR_HOST_ARCH}")
endif()
if(NOT DAGOR_DEPS_DIR)
  message(FATAL_ERROR "The Dagor toolchain files need DAGOR_DEPS_DIR; include prog/cmake/DagorBootstrap.cmake before project()")
endif()

# dagor_toolchain_forward(<var>...): makes the values visible to the try_compile projects
macro(dagor_toolchain_forward)
  list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ${ARGN})
  list(REMOVE_DUPLICATES CMAKE_TRY_COMPILE_PLATFORM_VARIABLES)
endmacro()
dagor_toolchain_forward(DAGOR_ARCH DAGOR_DEPS_DIR DAGOR_COMPILER)

# dagor_tool_version(<exe> <out-var>): the first x.y.z in the output of '<exe> --version'
function(dagor_tool_version exe out)
  execute_process(COMMAND "${exe}" --version OUTPUT_VARIABLE text ERROR_VARIABLE text RESULT_VARIABLE result)
  set(version "")
  if(result EQUAL 0 AND text MATCHES "([0-9]+\\.[0-9]+\\.[0-9]+)")
    set(version "${CMAKE_MATCH_1}")
  endif()
  set(${out} "${version}" PARENT_SCOPE)
endfunction()

# dagor_toolchain_llvm(): DAGOR_LLVM_DIR, an LLVM of the pinned version. An explicit -DDAGOR_LLVM_DIR wins; then an
# installed LLVM of that version (the official Windows installer's dir, or one on PATH); otherwise the release archive
# is fetched into the deps cache.
function(dagor_toolchain_llvm)
  dagor_sdk_version(llvm want)
  if(DAGOR_LLVM_DIR)
    set(dir "${DAGOR_LLVM_DIR}")
  else()
    set(dir "")
    set(candidates)
    if(CMAKE_HOST_WIN32)
      list(APPEND candidates "$ENV{ProgramFiles}/LLVM")
    endif()
    find_program(_dagor_clang_on_path NAMES clang NO_CACHE)
    if(_dagor_clang_on_path)
      cmake_path(GET _dagor_clang_on_path PARENT_PATH bin)
      cmake_path(GET bin PARENT_PATH root)
      list(APPEND candidates "${root}")
    endif()
    foreach(candidate IN LISTS candidates)
      file(TO_CMAKE_PATH "${candidate}" candidate)
      if(EXISTS "${candidate}/bin/clang${CMAKE_HOST_EXECUTABLE_SUFFIX}")
        dagor_tool_version("${candidate}/bin/clang${CMAKE_HOST_EXECUTABLE_SUFFIX}" have)
        if(have STREQUAL want)
          set(dir "${candidate}")
          break()
        endif()
      endif()
    endforeach()
    if(NOT dir)
      dagor_fetch_sdk(llvm dir)
    endif()
  endif()
  dagor_tool_version("${dir}/bin/clang${CMAKE_HOST_EXECUTABLE_SUFFIX}" have)
  if(NOT have STREQUAL want)
    message(FATAL_ERROR "DAGOR_LLVM_DIR='${dir}' is LLVM '${have}', the engine pins ${want}")
  endif()
  set(DAGOR_LLVM_DIR "${dir}" CACHE PATH "LLVM ${want} used by the build" FORCE)
  set(DAGOR_LLVM_VERSION "${want}" CACHE INTERNAL "")
endfunction()
