# DAGOR_PYTHON: the Python of the build's code generators. dagor_python() makes a venv with the hash-pinned packages
# of prog/cmake/python/requirements.txt in the deps cache, once per requirements content, the first time a target needs it.
include_guard(GLOBAL)

find_package(Python3 3.8 REQUIRED COMPONENTS Interpreter)

# dagor_python(<out-var>): the venv's interpreter
function(dagor_python out)
  if(DAGOR_PYTHON)
    set(${out} "${DAGOR_PYTHON}" PARENT_SCOPE)
    return()
  endif()
  set(requirements "${DAGOR_CMAKE_DIR}/python/requirements.txt")
  file(SHA256 "${requirements}" hash)
  string(SUBSTRING "${hash}" 0 12 hash)
  set(venv "${DAGOR_DEPS_DIR}/python/venv-${Python3_VERSION_MAJOR}.${Python3_VERSION_MINOR}-${hash}")
  if(CMAKE_HOST_WIN32)
    set(python "${venv}/Scripts/python.exe")
  else()
    set(python "${venv}/bin/python")
  endif()
  set(stamp "${venv}/.dagor-venv")

  if(NOT EXISTS "${stamp}")
    file(MAKE_DIRECTORY "${DAGOR_DEPS_DIR}/python")
    file(LOCK "${venv}.lock" GUARD FUNCTION TIMEOUT 1800)
    if(NOT EXISTS "${stamp}")
      message(STATUS "Creating the codegen Python venv in ${venv}")
      file(REMOVE_RECURSE "${venv}")
      execute_process(COMMAND "${Python3_EXECUTABLE}" -m venv "${venv}" RESULT_VARIABLE result)
      if(NOT result EQUAL 0)
        message(FATAL_ERROR "Creating a venv with ${Python3_EXECUTABLE} failed")
      endif()
      execute_process(COMMAND "${python}" -m pip install --disable-pip-version-check --no-input --require-hashes
                              -r "${requirements}" RESULT_VARIABLE result)
      if(NOT result EQUAL 0)
        file(REMOVE_RECURSE "${venv}")
        message(FATAL_ERROR "Installing ${requirements} into the codegen venv failed")
      endif()
      file(WRITE "${stamp}" "${requirements}\n")
    endif()
  endif()
  set(DAGOR_PYTHON "${python}" CACHE INTERNAL "The codegen Python")
  set(${out} "${python}" PARENT_SCOPE)
endfunction()
