# Targets of the engine and of projects: dagor_add_library(), dagor_add_executable(), dagor_add_shared_library(),
# and the loading of engine directories on demand.
#
# Library references. DEPS and PUBLIC_DEPS name targets, or engine directories under prog/ ('engine/math',
# '3rdPartyLibs/eastl'). A directory reference names the default target of that directory, its path with '/' as '.'
# ('engine.math'), and makes dagor_finalize() add the directory to the tree. Only the directories some target uses are
# configured, as with jam's UseProgLibs; dagor_use() asks for directories nothing links to (test programs, tools), and
# DAGOR_ADD_ALL adds every one.
#
# Static libraries link their DEPS privately, so a dependency's include dirs and definitions are not inherited by the
# library's users: a library that exposes a dependency's headers in its own lists it in PUBLIC_DEPS.
include_guard(GLOBAL)

set(DAGOR_PROG_DIR "${DAGOR_ENGINE_ROOT}/prog")

# dagor_ref_target(<ref> <out-var>): the target name a library reference stands for
function(dagor_ref_target ref out)
  if(ref MATCHES "/" AND NOT ref MATCHES "::|^\\$<")
    string(REGEX REPLACE "/+$" "" ref "${ref}")
    string(REPLACE "/" "." ref "${ref}")
  endif()
  set(${out} "${ref}" PARENT_SCOPE)
endfunction()

# dagor_use(<engine-dir>...): the directories (relative to prog/) are added to the tree by dagor_finalize()
function(dagor_use)
  foreach(ref IN LISTS ARGN)
    _dagor_queue_dir("${ref}" "${CMAKE_CURRENT_SOURCE_DIR}")
  endforeach()
endfunction()

function(_dagor_queue_dir ref requester)
  string(REGEX REPLACE "/+$" "" ref "${ref}")
  get_property(known GLOBAL PROPERTY DAGOR_KNOWN_DIRS)
  if(ref IN_LIST known)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY DAGOR_KNOWN_DIRS "${ref}")
  set_property(GLOBAL APPEND PROPERTY DAGOR_PENDING_DIRS "${ref}")
  set_property(GLOBAL PROPERTY DAGOR_DIR_${ref}_REQUESTER "${requester}")
endfunction()

# the reference of the engine directory <dir> ('engine/math'), or empty when it is not under prog/
function(_dagor_dir_ref dir out)
  cmake_path(IS_PREFIX DAGOR_PROG_DIR "${dir}" NORMALIZE inside)
  if(inside)
    cmake_path(RELATIVE_PATH dir BASE_DIRECTORY "${DAGOR_PROG_DIR}" OUTPUT_VARIABLE rel)
    set(${out} "${rel}" PARENT_SCOPE)
  else()
    set(${out} "" PARENT_SCOPE)
  endif()
endfunction()

# links <target> to library references, queueing the engine directories they name
function(_dagor_link target scope)
  foreach(ref IN LISTS ARGN)
    if(ref MATCHES "/" AND NOT ref MATCHES "::|^\\$<|^-")
      _dagor_queue_dir("${ref}" "${CMAKE_CURRENT_SOURCE_DIR}")
      dagor_ref_target("${ref}" name)
      set_property(GLOBAL APPEND PROPERTY DAGOR_REQUIRED_TARGETS "${name}")
      set_property(GLOBAL APPEND PROPERTY DAGOR_TARGET_${name}_USERS "${target}")
      target_link_libraries(${target} ${scope} "${name}")
    else()
      target_link_libraries(${target} ${scope} "${ref}")
    endif()
  endforeach()
endfunction()

# makes relative paths absolute (relative to the calling directory); generator expressions are kept as they are
function(_dagor_abs_paths out)
  set(result)
  foreach(path IN LISTS ARGN)
    if(path MATCHES "^\\$<" OR IS_ABSOLUTE "${path}")
      list(APPEND result "${path}")
    else()
      list(APPEND result "${CMAKE_CURRENT_SOURCE_DIR}/${path}")
    endif()
  endforeach()
  set(${out} "${result}" PARENT_SCOPE)
endfunction()

set(_DAGOR_TARGET_OPTIONS STRICT THIRD_PARTY NO_UNITY CONSOLE NO_CONFIG_POSTFIX)
set(_DAGOR_TARGET_ONE_VALUE PCH FOLDER OUTPUT_NAME OUTPUT_DIR EXCEPTIONS RTTI)
set(_DAGOR_TARGET_MULTI_VALUE SOURCES SOURCE_DIRS GLOB EXCLUDE PUBLIC_INCLUDES PRIVATE_INCLUDES PUBLIC_DEFINES
  PRIVATE_DEFINES COMPILE_OPTIONS C_OPTIONS PUBLIC_COMPILE_OPTIONS SOURCE_OPTIONS DEPS PUBLIC_DEPS SYSTEM_LIBS LINK_OPTIONS
  LICENSE_FILES)

# the settings dagor_add_library / _executable / _shared_library share; <type> is a CMake target type
function(_dagor_setup_target target type)
  cmake_parse_arguments(PARSE_ARGV 2 arg "${_DAGOR_TARGET_OPTIONS}" "${_DAGOR_TARGET_ONE_VALUE}"
                        "${_DAGOR_TARGET_MULTI_VALUE}")
  if(arg_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "${target}: unexpected arguments: ${arg_UNPARSED_ARGUMENTS}")
  endif()

  # sources: the listed files plus the scanned dirs (jam's Autoscan); *.gen.es.cpp are made by the ES codegen
  _dagor_abs_paths(sources ${arg_SOURCES})
  if(arg_SOURCE_DIRS)
    if(NOT arg_GLOB)
      set(arg_GLOB *.cpp *.c)
    endif()
    _dagor_abs_paths(dirs ${arg_SOURCE_DIRS})
    foreach(dir IN LISTS dirs)
      set(patterns ${arg_GLOB})
      list(TRANSFORM patterns PREPEND "${dir}/")
      file(GLOB found CONFIGURE_DEPENDS ${patterns})
      list(FILTER found EXCLUDE REGEX "\\.gen\\.es\\.cpp$")
      foreach(regex IN LISTS arg_EXCLUDE)
        list(FILTER found EXCLUDE REGEX "${regex}")
      endforeach()
      list(SORT found)
      list(APPEND sources ${found})
    endforeach()
  endif()

  if(type STREQUAL "INTERFACE_LIBRARY")
    set(public INTERFACE)
    set(private INTERFACE)
  else()
    set(public PUBLIC)
    set(private PRIVATE)
    target_sources(${target} PRIVATE ${sources})
    target_link_libraries(${target} PRIVATE Dagor::BuildSettings)
    string(FIND "${CMAKE_CURRENT_SOURCE_DIR}/" "/3rdPartyLibs/" third_party_dir)
    if(arg_STRICT AND NOT arg_THIRD_PARTY AND third_party_dir EQUAL -1)
      target_link_libraries(${target} PRIVATE Dagor::Strict)
      if(DAGOR_WARNINGS_AS_ERRORS)
        set_property(TARGET ${target} PROPERTY COMPILE_WARNING_AS_ERROR ON)
      endif()
    else()
      target_link_libraries(${target} PRIVATE Dagor::Lax)
    endif()
  endif()

  _dagor_abs_paths(public_includes ${arg_PUBLIC_INCLUDES})
  _dagor_abs_paths(private_includes ${arg_PRIVATE_INCLUDES})
  if(public_includes)
    target_include_directories(${target} ${public} ${public_includes})
  endif()
  if(private_includes)
    target_include_directories(${target} ${private} ${private_includes})
  endif()
  if(arg_PUBLIC_DEFINES)
    target_compile_definitions(${target} ${public} ${arg_PUBLIC_DEFINES})
  endif()
  if(arg_PRIVATE_DEFINES)
    target_compile_definitions(${target} ${private} ${arg_PRIVATE_DEFINES})
  endif()
  if(arg_PUBLIC_COMPILE_OPTIONS)
    target_compile_options(${target} ${public} ${arg_PUBLIC_COMPILE_OPTIONS})
  endif()
  if(arg_COMPILE_OPTIONS)
    target_compile_options(${target} ${private} ${arg_COMPILE_OPTIONS})
  endif()
  if(arg_C_OPTIONS)
    target_compile_options(${target} ${private} "$<$<COMPILE_LANGUAGE:C>:${arg_C_OPTIONS}>")
  endif()
  if(arg_LINK_OPTIONS)
    target_link_options(${target} ${private} ${arg_LINK_OPTIONS})
  endif()
  if(arg_SYSTEM_LIBS)
    target_link_libraries(${target} ${public} ${arg_SYSTEM_LIBS})
  endif()
  _dagor_link(${target} ${private} ${arg_DEPS})
  _dagor_link(${target} ${public} ${arg_PUBLIC_DEPS})

  # SOURCE_OPTIONS <file> <option>... [<file> <option>...]: options of single files (jam's 'opt on')
  set(file "")
  foreach(item IN LISTS arg_SOURCE_OPTIONS)
    if(item MATCHES "\\.(c|cc|cpp|cxx|m|mm|s|S|asm|inl)$")
      _dagor_abs_paths(file "${item}")
    elseif(NOT file)
      message(FATAL_ERROR "${target}: SOURCE_OPTIONS must start with a source file, not '${item}'")
    else()
      set_property(SOURCE "${file}" TARGET_DIRECTORY ${target} APPEND PROPERTY COMPILE_OPTIONS "${item}")
    endif()
  endforeach()

  if(type STREQUAL "INTERFACE_LIBRARY")
    return()
  endif()
  foreach(prop EXCEPTIONS RTTI)
    if(DEFINED arg_${prop})
      dagor_check_choice("${target} ${prop}" "${arg_${prop}}" ON OFF)
      set_property(TARGET ${target} PROPERTY DAGOR_${prop} "${arg_${prop}}")
    endif()
  endforeach()
  if(arg_PCH)
    _dagor_abs_paths(pch "${arg_PCH}")
    target_precompile_headers(${target} PRIVATE "${pch}")
  endif()
  if(DAGOR_UNITY_BUILD AND NOT arg_NO_UNITY)
    set_property(TARGET ${target} PROPERTY UNITY_BUILD ON)
  endif()
  if(arg_FOLDER)
    set_property(TARGET ${target} PROPERTY FOLDER "${arg_FOLDER}")
  else()
    _dagor_dir_ref("${CMAKE_CURRENT_SOURCE_DIR}" ref)
    if(ref)
      cmake_path(GET ref PARENT_PATH folder)
      set_property(TARGET ${target} PROPERTY FOLDER "${folder}")
    endif()
  endif()
  _dagor_abs_paths(licenses ${arg_LICENSE_FILES})
  set_property(TARGET ${target} PROPERTY DAGOR_LICENSE_FILES "${licenses}")

  if(type MATCHES "^(EXECUTABLE|SHARED_LIBRARY|MODULE_LIBRARY)$")
    # <name>[-asan|-ubsan|...][-cov]-<config>, as jam names programs; rel builds have no config suffix
    set(output_name "${target}")
    if(arg_OUTPUT_NAME)
      set(output_name "${arg_OUTPUT_NAME}")
    endif()
    set(san_address asan)
    set(san_undefined ubsan)
    set(san_thread tsan)
    set(san_leak lsan)
    set(san_memory msan)
    if(NOT DAGOR_SANITIZE STREQUAL "none")
      string(APPEND output_name "-${san_${DAGOR_SANITIZE}}")
    endif()
    if(DAGOR_COVERAGE)
      string(APPEND output_name "-cov")
    endif()
    set_property(TARGET ${target} PROPERTY OUTPUT_NAME "${output_name}")
    if(NOT arg_NO_CONFIG_POSTFIX)
      set_target_properties(${target} PROPERTIES DEV_POSTFIX -dev IREL_POSTFIX -irel DBG_POSTFIX -dbg)
    endif()
    if(arg_OUTPUT_DIR)
      _dagor_abs_paths(output_dir "${arg_OUTPUT_DIR}")
    else()
      set(output_dir "${CMAKE_BINARY_DIR}/bin")
    endif()
    # one dir for every configuration: the names differ by their postfix ($<1:> stops the per-config subdirs)
    set_target_properties(${target} PROPERTIES
      RUNTIME_OUTPUT_DIRECTORY "$<1:${output_dir}>"
      LIBRARY_OUTPUT_DIRECTORY "$<1:${output_dir}>"
      PDB_OUTPUT_DIRECTORY "$<1:${output_dir}>")
  endif()
  if(type STREQUAL "EXECUTABLE" AND DAGOR_PLATFORM STREQUAL "windows" AND NOT arg_CONSOLE)
    set_property(TARGET ${target} PROPERTY WIN32_EXECUTABLE ON)
  endif()

  set_property(GLOBAL APPEND PROPERTY DAGOR_TARGETS "${target}")
endfunction()

# the default name of a target declared in an engine directory: its path under prog/ with '/' as '.'
function(_dagor_target_name out first)
  if(first AND NOT first IN_LIST _DAGOR_TARGET_OPTIONS AND NOT first IN_LIST _DAGOR_TARGET_ONE_VALUE
     AND NOT first IN_LIST _DAGOR_TARGET_MULTI_VALUE AND NOT first MATCHES "^(STATIC|SHARED|OBJECT|INTERFACE)$")
    set(${out} "${first}" PARENT_SCOPE)
    set(${out}_GIVEN ON PARENT_SCOPE)
    return()
  endif()
  _dagor_dir_ref("${CMAKE_CURRENT_SOURCE_DIR}" ref)
  if(NOT ref)
    message(FATAL_ERROR "Targets outside the engine's prog/ need a name (${CMAKE_CURRENT_SOURCE_DIR})")
  endif()
  dagor_ref_target("${ref}" name)
  set(${out} "${name}" PARENT_SCOPE)
  set(${out}_GIVEN OFF PARENT_SCOPE)
endfunction()

# dagor_add_library([<name>] [STATIC|OBJECT|INTERFACE] [SOURCES ...] [SOURCE_DIRS <dir>... [GLOB <pattern>...]
#   [EXCLUDE <regex>...]] [PUBLIC_INCLUDES ...] [PRIVATE_INCLUDES ...] [PUBLIC_DEFINES ...] [PRIVATE_DEFINES ...]
#   [COMPILE_OPTIONS ...] [C_OPTIONS <options of the C sources>...] [PUBLIC_COMPILE_OPTIONS ...] [SOURCE_OPTIONS <file> <option>...] [DEPS <ref>...]
#   [PUBLIC_DEPS <ref>...] [SYSTEM_LIBS ...] [LINK_OPTIONS ...] [STRICT] [THIRD_PARTY] [EXCEPTIONS ON|OFF]
#   [RTTI ON|OFF] [PCH <header>] [NO_UNITY] [FOLDER <folder>] [LICENSE_FILES ...])
# <name> defaults to the directory's path under prog/ with '/' as '.' (see dagor_ref_target).
function(dagor_add_library)
  _dagor_target_name(name "${ARGV0}")
  set(args ${ARGN})
  if(name_GIVEN)
    list(POP_FRONT args)
  endif()
  set(type STATIC)
  list(GET args 0 first)
  if(first MATCHES "^(STATIC|OBJECT|INTERFACE)$")
    set(type "${first}")
    list(POP_FRONT args)
  endif()
  add_library(${name} ${type})
  get_property(cmake_type TARGET ${name} PROPERTY TYPE)
  _dagor_setup_target(${name} ${cmake_type} ${args})
endfunction()

# dagor_add_shared_library(<name> ...): a DLL / shared object, with dagor_add_library's options and OUTPUT_DIR,
# OUTPUT_NAME, NO_CONFIG_POSTFIX
function(dagor_add_shared_library name)
  add_library(${name} SHARED)
  _dagor_setup_target(${name} SHARED_LIBRARY ${ARGN})
endfunction()

# dagor_add_executable(<name> [CONSOLE] [OUTPUT_DIR <dir>] [OUTPUT_NAME <name>] [NO_CONFIG_POSTFIX] ...): a program,
# with dagor_add_library's options. It is named <name>[-asan...][-cov]-<config>, without the config suffix in Rel, in
# OUTPUT_DIR (default <build>/bin). Without CONSOLE it is a GUI (/SUBSYSTEM:WINDOWS) program on Windows.
function(dagor_add_executable name)
  add_executable(${name})
  _dagor_setup_target(${name} EXECUTABLE ${ARGN})
endfunction()

# dagor_finalize(): the last call of the top-level CMakeLists.txt. It adds the engine directories the targets use
# (and every one with DAGOR_ADD_ALL), until no new ones are needed, then checks that every reference resolved.
function(dagor_finalize)
  if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    message(FATAL_ERROR "dagor_finalize() belongs at the end of the top-level CMakeLists.txt")
  endif()
  get_property(done GLOBAL PROPERTY DAGOR_FINALIZED)
  if(done)
    message(FATAL_ERROR "dagor_finalize() was called twice")
  endif()
  set_property(GLOBAL PROPERTY DAGOR_FINALIZED ON)

  if(DAGOR_ADD_ALL)
    file(GLOB_RECURSE lists RELATIVE "${DAGOR_PROG_DIR}" "${DAGOR_PROG_DIR}/*/CMakeLists.txt")
    foreach(list IN LISTS lists)
      file(STRINGS "${DAGOR_PROG_DIR}/${list}" uses REGEX "dagor_add_" LIMIT_COUNT 1)
      if(uses)
        cmake_path(GET list PARENT_PATH ref)
        _dagor_queue_dir("${ref}" "DAGOR_ADD_ALL")
      endif()
    endforeach()
  endif()

  get_property(pending GLOBAL PROPERTY DAGOR_PENDING_DIRS)
  while(pending)
    list(POP_FRONT pending ref)
    set_property(GLOBAL PROPERTY DAGOR_PENDING_DIRS "${pending}")
    if(NOT EXISTS "${DAGOR_PROG_DIR}/${ref}/CMakeLists.txt")
      get_property(requester GLOBAL PROPERTY DAGOR_DIR_${ref}_REQUESTER)
      message(FATAL_ERROR "${requester} uses prog/${ref}, which has no CMakeLists.txt")
    endif()
    add_subdirectory("${DAGOR_PROG_DIR}/${ref}" "${CMAKE_BINARY_DIR}/_e/${ref}")
    get_property(pending GLOBAL PROPERTY DAGOR_PENDING_DIRS)
  endwhile()

  get_property(required GLOBAL PROPERTY DAGOR_REQUIRED_TARGETS)
  list(REMOVE_DUPLICATES required)
  set(missing)
  foreach(name IN LISTS required)
    if(NOT TARGET ${name})
      get_property(users GLOBAL PROPERTY DAGOR_TARGET_${name}_USERS)
      list(REMOVE_DUPLICATES users)
      list(JOIN users ", " users)
      list(APPEND missing "  ${name} (used by ${users})")
    endif()
  endforeach()
  if(missing)
    list(JOIN missing "\n" missing)
    message(FATAL_ERROR "Library references to directories that declare no target of that name:\n${missing}")
  endif()
endfunction()
