# The physics engine of the tree (jam's PhysName, prog/3rdPartyLibs/phys/setup-phys.jam): Dagor::Phys, which the
# libraries that use it link, carries its definitions, include dir and engine/phys library. DAGOR_PHYS is Jolt, or
# Bullet in the tool trees.
include_guard(GLOBAL)

add_library(DagorPhys INTERFACE)
add_library(Dagor::Phys ALIAS DagorPhys)
_dagor_configs_cond(_dagor_phys_checked ${DAGOR_CHECKED_CONTAINERS_CONFIGS})
# Jolt's own settings (joltPhysics/setup.jam), for Jolt, engine/phys/physJolt and the users of Dagor::Phys
add_library(DagorJoltSettings INTERFACE)
add_library(Dagor::JoltSettings ALIAS DagorJoltSettings)
target_compile_definitions(DagorJoltSettings INTERFACE JPH_CROSS_PLATFORM_DETERMINISTIC JPH_DEFAULT_ALLOCATE_ALIGNMENT=16)
# the asserts and the debug renderer in Dev and Dbg (not under TSan, whose checks they fail)
set(DAGOR_JOLT_DEBUG "$<CONFIG:Dev,Dbg>")
if(DAGOR_SANITIZE STREQUAL "thread")
  set(DAGOR_JOLT_DEBUG 0)
endif()
target_compile_definitions(DagorJoltSettings INTERFACE "$<${DAGOR_JOLT_DEBUG}:JPH_ENABLE_ASSERTS>"
  "$<${DAGOR_JOLT_DEBUG}:JPH_DEBUG_RENDERER>" "$<$<NOT:$<AND:${DAGOR_JOLT_DEBUG},${_dagor_phys_checked}>>:JPH_NO_DEBUG>")
if(DAGOR_ARCH STREQUAL "x86_64" AND DAGOR_SSE EQUAL 4)
  target_compile_definitions(DagorJoltSettings INTERFACE JPH_USE_SSE4_1 JPH_USE_SSE4_2) # SSE4.2 for popcnt
endif()
if(DAGOR_SANITIZE STREQUAL "address")
  target_compile_definitions(DagorJoltSettings INTERFACE JPH_DISABLE_TEMP_ALLOCATOR JPH_DISABLE_CUSTOM_ALLOCATOR)
endif()
if(DAGOR_ARCH STREQUAL "e2k")
  target_compile_options(DagorJoltSettings INTERFACE -w2810)
endif()

if(DAGOR_PHYS STREQUAL "Jolt")
  target_compile_definitions(DagorPhys INTERFACE USE_JOLT_PHYSICS)
  target_include_directories(DagorPhys INTERFACE "${DAGOR_PROG_DIR}/3rdPartyLibs/phys/joltPhysics")
  target_link_libraries(DagorPhys INTERFACE Dagor::JoltSettings)
  set(DAGOR_PHYS_DIR engine/phys/physJolt)
else()
  target_compile_definitions(DagorPhys INTERFACE USE_BULLET_PHYSICS BT_THREADSAFE "$<${_dagor_phys_checked}:BT_DEBUG>")
  if(NOT DAGOR_PLATFORM STREQUAL "macOS")
    target_compile_definitions(DagorPhys INTERFACE B3_USE_CLEW)
  endif()
  if(DAGOR_PLATFORM STREQUAL "android")
    target_compile_definitions(DagorPhys INTERFACE BT_USE_NEON BT_USE_SIMD_VECTOR3 BT_NO_SYSCTL)
  endif()
  target_include_directories(DagorPhys INTERFACE "${DAGOR_PROG_DIR}/3rdPartyLibs/phys/bullet-3/src")
  set(DAGOR_PHYS_DIR engine/phys/physBullet)
endif()
# the engine's physics library, added to the tree when a target links Dagor::Phys (see _dagor_link)
dagor_ref_target("${DAGOR_PHYS_DIR}" _dagor_phys_lib)
target_link_libraries(DagorPhys INTERFACE ${_dagor_phys_lib})
unset(_dagor_phys_lib)
