# Validation of cache option values, usable before project().
include_guard(GLOBAL)

# fails unless <value> is one of the values after it
function(dagor_check_choice name value)
  if(NOT value IN_LIST ARGN)
    list(JOIN ARGN ", " choices)
    message(FATAL_ERROR "${name}='${value}' is not supported; use one of: ${choices}")
  endif()
endfunction()

# fails unless platform, arch and compiler make a target the engine builds for
function(dagor_validate_target platform arch compiler)
  dagor_check_choice(DAGOR_PLATFORM "${platform}" windows linux macOS iOS tvOS android)
  set(archs_windows x86_64 arm64)
  set(archs_linux x86_64 e2k)
  set(archs_macOS x86_64 arm64 universal)
  set(archs_iOS arm64)
  set(archs_tvOS arm64)
  set(archs_android arm64)
  dagor_check_choice("DAGOR_ARCH for ${platform}" "${arch}" ${archs_${platform}})
  set(compilers_windows clang msvc)
  set(compilers_linux gcc clang)
  if(arch STREQUAL "e2k")
    set(compilers_linux lcc)
  endif()
  set(compilers_macOS clang)
  set(compilers_iOS clang)
  set(compilers_tvOS clang)
  set(compilers_android clang)
  dagor_check_choice("DAGOR_COMPILER for ${platform}-${arch}" "${compiler}" ${compilers_${platform}})

  set(hosts_windows windows)
  set(hosts_linux linux)
  set(hosts_macOS macOS)
  set(hosts_iOS macOS)
  set(hosts_tvOS macOS)
  set(hosts_android windows linux macOS)
  if(NOT DAGOR_HOST_PLATFORM IN_LIST hosts_${platform})
    message(FATAL_ERROR "DAGOR_PLATFORM=${platform} cannot be built on a ${DAGOR_HOST_PLATFORM} host")
  endif()
endfunction()
