# The LICENSE-<program> file next to every program and shared library: the licenses of the libraries it links, as jam
# wrote them. A library's licenses are the license files of its directory (License.*, LICENSE*, COPYING*, COPYRIGHT,
# ...) plus its LICENSE_FILES. A directory under 1stPartyLibs/ or 3rdPartyLibs/ without one fails the configure step,
# unless a NO_LICENSE file there says it needs none.

set(_DAGOR_LICENSE_GLOBS License.* license.* LICENSE.* LICENSE_*.txt license LICENSE COPYING copying COPYING.*
  COPYRIGHT copyright)

# the targets <target> links, directly or through other libraries; a reference inside a generator expression counts
# whatever its condition (both choices of a link choice, say), which can only add licenses
function(_dagor_link_closure target out)
  set(seen "${target}")
  set(queue "${target}")
  while(queue)
    list(POP_FRONT queue current)
    get_property(type TARGET ${current} PROPERTY TYPE)
    set(items)
    if(NOT type STREQUAL "INTERFACE_LIBRARY")
      get_property(items TARGET ${current} PROPERTY LINK_LIBRARIES)
    endif()
    get_property(interface TARGET ${current} PROPERTY INTERFACE_LINK_LIBRARIES)
    list(APPEND items ${interface})
    foreach(item IN LISTS items)
      string(REGEX REPLACE "[$<>:,]" ";" names "${item}")
      foreach(name IN LISTS names)
        if(name AND TARGET "${name}" AND NOT name IN_LIST seen)
          get_property(aliased TARGET "${name}" PROPERTY ALIASED_TARGET)
          if(aliased)
            set(name "${aliased}")
            if(name IN_LIST seen)
              continue()
            endif()
          endif()
          list(APPEND seen "${name}")
          list(APPEND queue "${name}")
        endif()
      endforeach()
    endforeach()
  endwhile()
  set(${out} "${seen}" PARENT_SCOPE)
endfunction()

# the license files of a directory; one under 1stPartyLibs/ or 3rdPartyLibs/ without any is added to <missing>
function(_dagor_dir_licenses dir out missing_var)
  get_property(cached GLOBAL PROPERTY "DAGOR_LICENSES_${dir}" SET)
  if(cached)
    get_property(found GLOBAL PROPERTY "DAGOR_LICENSES_${dir}")
  else()
    set(patterns ${_DAGOR_LICENSE_GLOBS})
    list(TRANSFORM patterns PREPEND "${dir}/")
    file(GLOB found LIST_DIRECTORIES false ${patterns})
    list(SORT found)
    set_property(GLOBAL PROPERTY "DAGOR_LICENSES_${dir}" "${found}")
  endif()
  if(NOT found AND dir MATCHES "/(1st|3rd)PartyLibs/" AND NOT EXISTS "${dir}/NO_LICENSE")
    set(${missing_var} ${${missing_var}} "${dir}" PARENT_SCOPE)
  endif()
  set(${out} "${found}" PARENT_SCOPE)
endfunction()

# the license files of a target: those of its directory (not for the program itself, as in jam), and its
# LICENSE_FILES (files, or directories to look in)
function(_dagor_target_licenses target program out missing_var)
  set(result)
  set(lacking ${${missing_var}})
  set(dir)
  if(NOT target STREQUAL program)
    get_property(dir TARGET ${target} PROPERTY DAGOR_SOURCE_DIR)
  endif()
  get_property(explicit TARGET ${target} PROPERTY DAGOR_LICENSE_FILES)
  foreach(path IN LISTS dir explicit)
    if(IS_DIRECTORY "${path}")
      _dagor_dir_licenses("${path}" found lacking)
      list(APPEND result ${found})
    elseif(path)
      list(APPEND result "${path}")
    endif()
  endforeach()
  set(${missing_var} ${lacking} PARENT_SCOPE)
  set(${out} "${result}" PARENT_SCOPE)
endfunction()

# writes <file> only when its content changes, so programs do not relink the license copy needlessly
function(_dagor_write_if_changed file content)
  if(EXISTS "${file}")
    file(READ "${file}" old)
    if(old STREQUAL content)
      return()
    endif()
  endif()
  file(WRITE "${file}" "${content}")
endfunction()

# called by dagor_finalize()
function(_dagor_licenses)
  get_property(targets GLOBAL PROPERTY DAGOR_TARGETS)
  set(missing)
  foreach(target IN LISTS targets)
    get_property(type TARGET ${target} PROPERTY TYPE)
    if(NOT type MATCHES "^(EXECUTABLE|SHARED_LIBRARY|MODULE_LIBRARY)$")
      continue()
    endif()
    _dagor_link_closure(${target} closure)
    set(files)
    foreach(lib IN LISTS closure)
      _dagor_target_licenses(${lib} ${target} lib_files missing)
      list(APPEND files ${lib_files})
    endforeach()
    list(REMOVE_DUPLICATES files)
    if(NOT files)
      continue()
    endif()
    # one text per configuration, headed by the program's file name, which differs by its postfix
    set(body "")
    foreach(file IN LISTS files)
      cmake_path(GET file PARENT_PATH lib_dir)
      cmake_path(GET lib_dir FILENAME lib_name)
      file(READ "${file}" bom LIMIT 3 HEX)
      if(bom STREQUAL "efbbbf") # the UTF-8 byte order mark is dropped
        file(READ "${file}" text OFFSET 3)
      else()
        file(READ "${file}" text)
      endif()
      string(APPEND body "\n==== ${lib_name}\n\n${text}")
    endforeach()
    get_property(name TARGET ${target} PROPERTY OUTPUT_NAME)
    if(type STREQUAL "EXECUTABLE")
      set(suffix "${CMAKE_EXECUTABLE_SUFFIX}")
    else()
      set(suffix "${CMAKE_SHARED_LIBRARY_SUFFIX}")
    endif()
    set(dir "${CMAKE_BINARY_DIR}/licenses")
    foreach(config IN LISTS CMAKE_CONFIGURATION_TYPES CMAKE_BUILD_TYPE)
      string(TOUPPER "${config}" upper)
      get_property(postfix TARGET ${target} PROPERTY ${upper}_POSTFIX)
      _dagor_write_if_changed("${dir}/${target}-${config}.txt" "${name}${postfix}${suffix} uses libraries:\n${body}")
    endforeach()
    # copied next to the program by a target it depends on (a POST_BUILD step can only be added in its directory)
    add_custom_target(${target}.license
      COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:${target}>"
      COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${dir}/${target}-$<CONFIG>.txt"
        "$<TARGET_FILE_DIR:${target}>/LICENSE-$<TARGET_FILE_BASE_NAME:${target}>"
      COMMENT "LICENSE-${name} for ${target}"
      VERBATIM)
    set_property(TARGET ${target}.license PROPERTY FOLDER "licenses")
    add_dependencies(${target} ${target}.license)
    set_property(TARGET ${target} PROPERTY DAGOR_LICENSE_TEXT "${dir}/${target}-$<CONFIG>.txt")
  endforeach()
  if(missing)
    list(REMOVE_DUPLICATES missing)
    list(JOIN missing "\n  " missing)
    message(FATAL_ERROR "Libraries without a license file (add it, or a NO_LICENSE file if none is needed):\n"
      "  ${missing}")
  endif()
endfunction()
