# The system libraries the targets link on Linux (SYSTEM_LIBS of dagor_add_*), checked once the tree is complete: a
# missing one fails the configure with the packages to install, instead of failing the link later.
include_guard(GLOBAL)

# library -> package, for the apt (Debian, Ubuntu, Astra) and dnf/urpmi (Fedora, CentOS, ROSA, ALT) families
set(_dagor_pkg_apt_X11 libx11-dev)
set(_dagor_pkg_apt_Xrandr libxrandr-dev)
set(_dagor_pkg_apt_Xcursor libxcursor-dev)
set(_dagor_pkg_apt_xkbcommon libxkbcommon-dev)
set(_dagor_pkg_apt_xkbfile libxkbfile-dev)
set(_dagor_pkg_apt_fltk libfltk1.3-dev)
set(_dagor_pkg_apt_udev libudev-dev)
set(_dagor_pkg_apt_pulse libpulse-dev)
set(_dagor_pkg_apt_asound libasound2-dev)
set(_dagor_pkg_apt_uuid uuid-dev)
set(_dagor_pkg_rpm_X11 libX11-devel)
set(_dagor_pkg_rpm_Xrandr libXrandr-devel)
set(_dagor_pkg_rpm_Xcursor libXcursor-devel)
set(_dagor_pkg_rpm_xkbcommon libxkbcommon-devel)
set(_dagor_pkg_rpm_xkbfile libxkbfile-devel)
set(_dagor_pkg_rpm_fltk fltk-devel)
set(_dagor_pkg_rpm_udev systemd-devel)
set(_dagor_pkg_rpm_pulse pulseaudio-libs-devel)
set(_dagor_pkg_rpm_asound alsa-lib-devel)
set(_dagor_pkg_rpm_uuid libuuid-devel)
# provided by the C library or the toolchain
set(_dagor_system_libs_builtin rt pthread dl m stdc++)

# records the plain library names <target> links, for dagor_check_system_libs()
function(_dagor_record_system_libs)
  if(NOT DAGOR_PLATFORM STREQUAL "linux")
    return()
  endif()
  foreach(lib IN LISTS ARGN)
    if(lib MATCHES "^[A-Za-z0-9_+.-]+$" AND NOT lib MATCHES "::" AND NOT lib IN_LIST _dagor_system_libs_builtin)
      set_property(GLOBAL APPEND PROPERTY DAGOR_SYSTEM_LIBS "${lib}")
    endif()
  endforeach()
endfunction()

function(dagor_check_system_libs)
  get_property(libs GLOBAL PROPERTY DAGOR_SYSTEM_LIBS)
  if(NOT libs)
    return()
  endif()
  list(REMOVE_DUPLICATES libs)
  set(missing)
  foreach(lib IN LISTS libs)
    find_library(DAGOR_SYSTEM_LIB_${lib} NAMES ${lib})
    if(NOT DAGOR_SYSTEM_LIB_${lib})
      list(APPEND missing ${lib})
    endif()
  endforeach()
  if(NOT missing)
    return()
  endif()
  if(EXISTS /usr/bin/apt-get)
    set(family apt)
    set(install "sudo apt-get install")
  elseif(EXISTS /usr/bin/dnf)
    set(family rpm)
    set(install "sudo dnf install")
  else()
    set(family rpm)
    set(install "install the development packages of:")
  endif()
  set(packages)
  foreach(lib IN LISTS missing)
    if(DEFINED _dagor_pkg_${family}_${lib})
      list(APPEND packages ${_dagor_pkg_${family}_${lib}})
    else()
      list(APPEND packages "<lib${lib}>")
    endif()
  endforeach()
  list(JOIN missing ", " missing)
  list(JOIN packages " " packages)
  message(FATAL_ERROR "System libraries missing: ${missing}\n  ${install} ${packages}")
endfunction()
