# Targets of the engine and of projects: dagor_add_library(), dagor_add_executable(), dagor_add_shared_library(),
# and the loading of engine directories on demand.
#
# Library references. DEPS and PUBLIC_DEPS name targets, or engine directories under prog/ ('engine/math',
# '3rdPartyLibs/eastl'). A directory reference names the default target of that directory, its path with '/' as '.'
# ('engine.math'), and makes dagor_finalize() add the directory to the tree. Only the directories some target uses are
# configured, as with jam's UseProgLibs; dagor_use() asks for directories nothing links to (test programs, tools), and
# DAGOR_ADD_ALL adds every one.
#
# Static libraries link their DEPS privately, so a dependency's include dirs and definitions are not inherited by the
# library's users: a library that exposes a dependency's headers in its own lists it in PUBLIC_DEPS.
#
# Flavors. A library that programs need built in different ways (memory allocators, driver sets: what jam selected
# with global variables) registers a function with dagor_flavors(<function>). A reference '<dir>:<flavor>'
# ('engine/memory:rtl.dbg') names the target '<dir as dots>.<flavor>' ('engine.memory.rtl.dbg'), which the function
# declares when something first asks for it. Flavor targets are built only for their users (EXCLUDE_FROM_ALL).
include_guard(GLOBAL)

include(DagorSystemLibs)

set(DAGOR_PROG_DIR "${DAGOR_ENGINE_ROOT}/prog")

# dagor_ref_target(<ref> <out-var>): the target name a library reference stands for
function(dagor_ref_target ref out)
  if(ref MATCHES "/" AND NOT ref MATCHES "::|^\\$<")
    string(REGEX REPLACE "/+(:|$)" "\\1" ref "${ref}")
    string(REPLACE "/" "." ref "${ref}")
    string(REPLACE ":" "." ref "${ref}")
  endif()
  set(${out} "${ref}" PARENT_SCOPE)
endfunction()

# the dir a target declaration resolves relative paths against: the calling dir, or the dir of a flavor function
macro(_dagor_base_dir out)
  if(_DAGOR_BASE_DIR)
    set(${out} "${_DAGOR_BASE_DIR}")
  else()
    set(${out} "${CMAKE_CURRENT_SOURCE_DIR}")
  endif()
endmacro()

# dagor_flavors(<function>): <function>(<flavor>) declares the flavor targets of the calling engine directory, named
# by dagor_flavor_target(); the default target (flavor "") is declared right away, the others on demand
function(dagor_flavors fn)
  _dagor_dir_ref("${CMAKE_CURRENT_SOURCE_DIR}" ref)
  if(NOT ref)
    message(FATAL_ERROR "dagor_flavors() is for engine directories under prog/")
  endif()
  set_property(GLOBAL PROPERTY DAGOR_FLAVORS_${ref}_FN "${fn}")
  set_property(GLOBAL PROPERTY DAGOR_FLAVORS_${ref}_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  _dagor_make_flavor("${ref}" "")
  get_property(requested GLOBAL PROPERTY DAGOR_FLAVORS_${ref}_REQUESTED)
  foreach(flavor IN LISTS requested)
    _dagor_make_flavor("${ref}" "${flavor}")
  endforeach()
endfunction()

# dagor_flavor_target(<flavor> <out-var>): the name of a flavor target of the directory whose flavor function runs
function(dagor_flavor_target flavor out)
  _dagor_base_dir(dir)
  _dagor_dir_ref("${dir}" ref)
  if(flavor STREQUAL "")
    dagor_ref_target("${ref}" name)
  else()
    dagor_ref_target("${ref}:${flavor}" name)
  endif()
  set(${out} "${name}" PARENT_SCOPE)
endfunction()

function(_dagor_make_flavor ref flavor)
  if(flavor STREQUAL "")
    dagor_ref_target("${ref}" name)
  else()
    dagor_ref_target("${ref}:${flavor}" name)
  endif()
  if(TARGET ${name})
    return()
  endif()
  get_property(fn GLOBAL PROPERTY DAGOR_FLAVORS_${ref}_FN)
  get_property(_DAGOR_BASE_DIR GLOBAL PROPERTY DAGOR_FLAVORS_${ref}_DIR)
  cmake_language(CALL ${fn} "${flavor}")
  if(NOT TARGET ${name})
    message(FATAL_ERROR "prog/${ref} has no flavor '${flavor}' (its flavor function ${fn} declared no ${name})")
  endif()
  if(NOT flavor STREQUAL "")
    set_property(TARGET ${name} PROPERTY EXCLUDE_FROM_ALL ON)
  endif()
endfunction()

# a reference to the flavor <flavor> of the engine dir <ref>: declared now when the dir is loaded, else at its loading
function(_dagor_request_flavor ref flavor)
  get_property(fn GLOBAL PROPERTY DAGOR_FLAVORS_${ref}_FN)
  if(fn)
    _dagor_make_flavor("${ref}" "${flavor}")
  else()
    set_property(GLOBAL APPEND PROPERTY DAGOR_FLAVORS_${ref}_REQUESTED "${flavor}")
  endif()
endfunction()

# dagor_use(<engine-dir>[:<flavor>]...): the directories (relative to prog/) are added to the tree by dagor_finalize(),
# and the flavors declared; for targets that link them through a generator expression, e.g. one flavor per config
function(dagor_use)
  foreach(ref IN LISTS ARGN)
    if(ref MATCHES "^([^:]+):(.+)$")
      _dagor_queue_dir("${CMAKE_MATCH_1}" "${CMAKE_CURRENT_SOURCE_DIR}")
      _dagor_request_flavor("${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
    else()
      _dagor_queue_dir("${ref}" "${CMAKE_CURRENT_SOURCE_DIR}")
    endif()
  endforeach()
endfunction()

function(_dagor_queue_dir ref requester)
  string(REGEX REPLACE "/+$" "" ref "${ref}")
  get_property(known GLOBAL PROPERTY DAGOR_KNOWN_DIRS)
  if(ref IN_LIST known)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY DAGOR_KNOWN_DIRS "${ref}")
  set_property(GLOBAL APPEND PROPERTY DAGOR_PENDING_DIRS "${ref}")
  set_property(GLOBAL PROPERTY DAGOR_DIR_${ref}_REQUESTER "${requester}")
endfunction()

# the reference of the engine directory <dir> ('engine/math'), or empty when it is not under prog/
function(_dagor_dir_ref dir out)
  cmake_path(IS_PREFIX DAGOR_PROG_DIR "${dir}" NORMALIZE inside)
  if(inside)
    cmake_path(RELATIVE_PATH dir BASE_DIRECTORY "${DAGOR_PROG_DIR}" OUTPUT_VARIABLE rel)
    set(${out} "${rel}" PARENT_SCOPE)
  else()
    set(${out} "" PARENT_SCOPE)
  endif()
endfunction()

# dagor_add_link_choice(<name> PROPERTY <property> ON <target> OFF <target>): an interface library that links <ON>
# into the programs whose <property> is true and <OFF> into the others. A program sets the property (PROPERTIES of
# dagor_add_executable), or gets it from a library it links that sets INTERFACE_<property> ON. This is how a choice
# jam made with a global variable is made per program when libraries in between depend on the chosen one; both
# implementations are built only for the programs that use them.
function(dagor_add_link_choice name)
  cmake_parse_arguments(PARSE_ARGV 1 arg "" "PROPERTY;ON;OFF" "")
  add_library(${name} INTERFACE)
  target_link_libraries(${name} INTERFACE "$<IF:$<BOOL:$<TARGET_PROPERTY:${arg_PROPERTY}>>,${arg_ON},${arg_OFF}>")
  set_property(TARGET ${name} APPEND PROPERTY COMPATIBLE_INTERFACE_BOOL ${arg_PROPERTY})
  foreach(impl ${arg_ON} ${arg_OFF})
    if(TARGET ${impl})
      set_property(TARGET ${impl} PROPERTY EXCLUDE_FROM_ALL ON)
    endif()
  endforeach()
endfunction()

# dagor_add_link_select(<name> PROPERTY <property> DEFAULT <target> [<value> <target>]...): like dagor_add_link_choice,
# for a string property: the programs whose <property> is <value> get that <target>, the others (and those without
# the property) get the DEFAULT one
function(dagor_add_link_select name)
  cmake_parse_arguments(PARSE_ARGV 1 arg "" "PROPERTY;DEFAULT" "")
  set(pairs ${arg_UNPARSED_ARGUMENTS})
  set(expr "${arg_DEFAULT}")
  set(targets ${arg_DEFAULT})
  set(property "$<TARGET_PROPERTY:${arg_PROPERTY}>")
  list(LENGTH pairs count)
  while(count GREATER 1)
    math(EXPR last "${count} - 1")
    math(EXPR value_index "${count} - 2")
    list(GET pairs ${value_index} value)
    list(GET pairs ${last} target)
    set(expr "$<IF:$<STREQUAL:${property},${value}>,${target},${expr}>")
    list(APPEND targets ${target})
    list(REMOVE_AT pairs ${value_index} ${last})
    list(LENGTH pairs count)
  endwhile()
  add_library(${name} INTERFACE)
  target_link_libraries(${name} INTERFACE "${expr}")
  set_property(TARGET ${name} APPEND PROPERTY COMPATIBLE_INTERFACE_STRING ${arg_PROPERTY})
  foreach(impl IN LISTS targets)
    if(TARGET ${impl})
      set_property(TARGET ${impl} PROPERTY EXCLUDE_FROM_ALL ON)
    endif()
  endforeach()
endfunction()

# links <target> to library references, queueing the engine directories they name
function(_dagor_link target scope)
  foreach(ref IN LISTS ARGN)
    if(ref MATCHES "/" AND NOT ref MATCHES "::|^\\$<|^-")
      if(ref MATCHES "^([^:]+):(.+)$")
        set(dir "${CMAKE_MATCH_1}")
        set(flavor "${CMAKE_MATCH_2}")
        _dagor_queue_dir("${dir}" "${CMAKE_CURRENT_SOURCE_DIR}")
        _dagor_request_flavor("${dir}" "${flavor}")
      else()
        _dagor_queue_dir("${ref}" "${CMAKE_CURRENT_SOURCE_DIR}")
      endif()
      dagor_ref_target("${ref}" name)
      set_property(GLOBAL APPEND PROPERTY DAGOR_REQUIRED_TARGETS "${name}")
      set_property(GLOBAL APPEND PROPERTY DAGOR_TARGET_${name}_USERS "${target}")
      target_link_libraries(${target} ${scope} "${name}")
    else()
      target_link_libraries(${target} ${scope} "${ref}")
    endif()
  endforeach()
endfunction()

# makes relative paths absolute (relative to the calling directory); generator expressions are kept as they are
function(_dagor_abs_paths out)
  _dagor_base_dir(base)
  set(result)
  foreach(path IN LISTS ARGN)
    if(path MATCHES "^\\$<" OR IS_ABSOLUTE "${path}")
      list(APPEND result "${path}")
    else()
      list(APPEND result "${base}/${path}")
    endif()
  endforeach()
  set(${out} "${result}" PARENT_SCOPE)
endfunction()

# Quirrel's headers and settings (jam's add_quirrel.jam), for QUIRREL and QUIRREL_HEADERS of dagor_add_*
add_library(DagorQuirrel INTERFACE)
add_library(Dagor::Quirrel ALIAS DagorQuirrel)
target_include_directories(DagorQuirrel INTERFACE
  "${DAGOR_PROG_DIR}/1stPartyLibs/quirrel/quirrel/include"
  "${DAGOR_PROG_DIR}/1stPartyLibs/quirrel/quirrel/sqrat/include"
  "${DAGOR_PROG_DIR}/1stPartyLibs/quirrel/quirrel"
  "${DAGOR_PROG_DIR}/gameLibs/publicInclude/quirrel/quirrelHost")
target_compile_definitions(DagorQuirrel INTERFACE QUIRREL_HOST_HEADER=dagor_quirrel_host.h USE_SQRAT_CONFIG
  "$<$<CONFIG:Rel,IRel>:SQ_STORE_DOC_OBJECTS=0>")
set(DAGOR_QUIRREL_LIBS 1stPartyLibs/quirrel/quirrel 1stPartyLibs/quirrel/quirrel/sqmodules gameLibs/quirrel/quirrelHost)

set(_DAGOR_TARGET_OPTIONS STRICT THIRD_PARTY NO_UNITY CONSOLE NO_CONFIG_POSTFIX QUIRREL QUIRREL_HEADERS)
set(_DAGOR_TARGET_ONE_VALUE PCH FOLDER OUTPUT_NAME OUTPUT_DIR EXCEPTIONS RTTI)
set(_DAGOR_TARGET_MULTI_VALUE SOURCES SOURCE_DIRS GLOB EXCLUDE FORCE_INCLUDES PUBLIC_INCLUDES PRIVATE_INCLUDES PUBLIC_DEFINES
  PRIVATE_DEFINES COMPILE_OPTIONS C_OPTIONS PUBLIC_COMPILE_OPTIONS SOURCE_OPTIONS DEPS PUBLIC_DEPS SYSTEM_LIBS LINK_OPTIONS
  LICENSE_FILES PROPERTIES STRINGIFY STRINGIFY_ARRAY)

# dagor_glob_sources(<out-var> DIRS <dir>... [GLOB <pattern>...] [EXCLUDE <regex>...]): appends to <out-var> the files
# of the dirs (relative to the calling dir, not recursive) that match the patterns (default *.cpp *.c), sorted;
# *.gen.es.cpp files are made by the ES codegen and never listed. jam's AutoscanBuildLists.
function(dagor_glob_sources out)
  cmake_parse_arguments(PARSE_ARGV 1 arg "" "" "DIRS;GLOB;EXCLUDE")
  if(NOT arg_GLOB)
    set(arg_GLOB *.cpp *.c)
  endif()
  set(result ${${out}})
  _dagor_abs_paths(dirs ${arg_DIRS})
  foreach(dir IN LISTS dirs)
    set(patterns ${arg_GLOB})
    list(TRANSFORM patterns PREPEND "${dir}/")
    file(GLOB found CONFIGURE_DEPENDS ${patterns})
    list(FILTER found EXCLUDE REGEX "\\.gen\\.es\\.cpp$")
    foreach(regex IN LISTS arg_EXCLUDE)
      list(FILTER found EXCLUDE REGEX "${regex}")
    endforeach()
    list(SORT found)
    list(APPEND result ${found})
  endforeach()
  set(${out} "${result}" PARENT_SCOPE)
endfunction()

# the settings dagor_add_library / _executable / _shared_library share; <type> is a CMake target type
function(_dagor_setup_target target type)
  cmake_parse_arguments(PARSE_ARGV 2 arg "${_DAGOR_TARGET_OPTIONS}" "${_DAGOR_TARGET_ONE_VALUE}"
                        "${_DAGOR_TARGET_MULTI_VALUE}")
  if(arg_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "${target}: unexpected arguments: ${arg_UNPARSED_ARGUMENTS}")
  endif()

  # sources: the listed files plus the scanned dirs (see dagor_glob_sources)
  _dagor_abs_paths(sources ${arg_SOURCES})
  if(arg_SOURCE_DIRS)
    dagor_glob_sources(sources DIRS ${arg_SOURCE_DIRS} GLOB ${arg_GLOB} EXCLUDE ${arg_EXCLUDE})
  endif()

  if(type STREQUAL "INTERFACE_LIBRARY")
    set(public INTERFACE)
    set(private INTERFACE)
  else()
    set(public PUBLIC)
    set(private PRIVATE)
    target_sources(${target} PRIVATE ${sources})
    # the assembler of a source by its extension, as jam chose it (CMake's own mapping lets MASM claim .asm)
    foreach(source IN LISTS sources)
      if(source MATCHES "\\.(asm|nasm|nas)$")
        set_property(SOURCE "${source}" TARGET_DIRECTORY ${target} PROPERTY LANGUAGE ASM_NASM)
      elseif(source MATCHES "\\.masm$")
        set_property(SOURCE "${source}" TARGET_DIRECTORY ${target} PROPERTY LANGUAGE ASM_MASM)
      elseif(source MATCHES "\\.[sS]$")
        set_property(SOURCE "${source}" TARGET_DIRECTORY ${target} PROPERTY LANGUAGE ASM)
      endif()
    endforeach()
    target_link_libraries(${target} PRIVATE Dagor::BuildSettings)
    target_include_directories(${target} BEFORE PRIVATE ${DAGOR_BASE_INCLUDES})
    _dagor_base_dir(base)
    string(FIND "${base}/" "/3rdPartyLibs/" third_party_dir)
    if(arg_STRICT AND NOT arg_THIRD_PARTY AND third_party_dir EQUAL -1)
      target_link_libraries(${target} PRIVATE Dagor::Strict)
      if(DAGOR_WARNINGS_AS_ERRORS)
        set_property(TARGET ${target} PROPERTY COMPILE_WARNING_AS_ERROR ON)
      endif()
    else()
      target_link_libraries(${target} PRIVATE Dagor::Lax)
    endif()
  endif()

  _dagor_abs_paths(public_includes ${arg_PUBLIC_INCLUDES})
  _dagor_abs_paths(private_includes ${arg_PRIVATE_INCLUDES})
  if(public_includes)
    target_include_directories(${target} ${public} ${public_includes})
  endif()
  if(private_includes)
    target_include_directories(${target} ${private} ${private_includes})
  endif()
  if(arg_PUBLIC_DEFINES)
    target_compile_definitions(${target} ${public} ${arg_PUBLIC_DEFINES})
  endif()
  if(arg_PRIVATE_DEFINES)
    target_compile_definitions(${target} ${private} ${arg_PRIVATE_DEFINES})
  endif()
  if(arg_PUBLIC_COMPILE_OPTIONS)
    target_compile_options(${target} ${public} ${arg_PUBLIC_COMPILE_OPTIONS})
  endif()
  if(arg_COMPILE_OPTIONS)
    target_compile_options(${target} ${private} ${arg_COMPILE_OPTIONS})
  endif()
  if(arg_C_OPTIONS)
    target_compile_options(${target} ${private} "$<$<COMPILE_LANGUAGE:C>:${arg_C_OPTIONS}>")
  endif()
  if(arg_LINK_OPTIONS)
    target_link_options(${target} ${private} ${arg_LINK_OPTIONS})
  endif()
  foreach(header IN LISTS arg_FORCE_INCLUDES)
    if(DAGOR_MSVC_LIKE)
      target_compile_options(${target} ${private} "$<$<COMPILE_LANGUAGE:C,CXX>:/FI${header}>")
    else()
      target_compile_options(${target} ${private} "$<$<COMPILE_LANGUAGE:C,CXX>:SHELL:-include ${header}>")
    endif()
  endforeach()
  if(arg_SYSTEM_LIBS)
    target_link_libraries(${target} ${public} ${arg_SYSTEM_LIBS})
    _dagor_record_system_libs(${arg_SYSTEM_LIBS})
  endif()
  if(arg_QUIRREL OR arg_QUIRREL_HEADERS)
    target_link_libraries(${target} ${private} Dagor::Quirrel)
  endif()
  if(arg_QUIRREL)
    _dagor_link(${target} ${private} ${DAGOR_QUIRREL_LIBS})
  endif()
  _dagor_link(${target} ${private} ${arg_DEPS})
  _dagor_link(${target} ${public} ${arg_PUBLIC_DEPS})
  if(arg_PROPERTIES)
    set_target_properties(${target} PROPERTIES ${arg_PROPERTIES})
  endif()
  if(arg_STRINGIFY)
    _dagor_stringify(${target} "" ${arg_STRINGIFY})
  endif()
  if(arg_STRINGIFY_ARRAY)
    _dagor_stringify(${target} --array ${arg_STRINGIFY_ARRAY})
  endif()

  # SOURCE_OPTIONS <file> <option>... [<file> <option>...]: options of single files (jam's 'opt on')
  set(file "")
  foreach(item IN LISTS arg_SOURCE_OPTIONS)
    if(item MATCHES "\\.(c|cc|cpp|cxx|m|mm|s|S|asm|inl)$")
      _dagor_abs_paths(file "${item}")
    elseif(NOT file)
      message(FATAL_ERROR "${target}: SOURCE_OPTIONS must start with a source file, not '${item}'")
    else()
      set_property(SOURCE "${file}" TARGET_DIRECTORY ${target} APPEND PROPERTY COMPILE_OPTIONS "${item}")
    endif()
  endforeach()

  if(type STREQUAL "INTERFACE_LIBRARY")
    return()
  endif()
  foreach(prop EXCEPTIONS RTTI)
    if(DEFINED arg_${prop})
      dagor_check_choice("${target} ${prop}" "${arg_${prop}}" ON OFF)
      set_property(TARGET ${target} PROPERTY DAGOR_${prop} "${arg_${prop}}")
    endif()
  endforeach()
  if(arg_PCH)
    _dagor_abs_paths(pch "${arg_PCH}")
    target_precompile_headers(${target} PRIVATE "${pch}")
  endif()
  if(DAGOR_UNITY_BUILD AND NOT arg_NO_UNITY)
    set_property(TARGET ${target} PROPERTY UNITY_BUILD ON)
  endif()
  if(arg_FOLDER)
    set_property(TARGET ${target} PROPERTY FOLDER "${arg_FOLDER}")
  else()
    _dagor_base_dir(base)
    _dagor_dir_ref("${base}" ref)
    if(ref)
      cmake_path(GET ref PARENT_PATH folder)
      set_property(TARGET ${target} PROPERTY FOLDER "${folder}")
    endif()
  endif()
  _dagor_abs_paths(licenses ${arg_LICENSE_FILES})
  set_property(TARGET ${target} PROPERTY DAGOR_LICENSE_FILES "${licenses}")

  if(type MATCHES "^(EXECUTABLE|SHARED_LIBRARY|MODULE_LIBRARY)$")
    # <name>[-asan|-ubsan|...][-cov]-<config>, as jam names programs; rel builds have no config suffix
    set(output_name "${target}")
    if(arg_OUTPUT_NAME)
      set(output_name "${arg_OUTPUT_NAME}")
    endif()
    set(san_address asan)
    set(san_undefined ubsan)
    set(san_thread tsan)
    set(san_leak lsan)
    set(san_memory msan)
    if(NOT DAGOR_SANITIZE STREQUAL "none")
      string(APPEND output_name "-${san_${DAGOR_SANITIZE}}")
    endif()
    if(DAGOR_COVERAGE)
      string(APPEND output_name "-cov")
    endif()
    set_property(TARGET ${target} PROPERTY OUTPUT_NAME "${output_name}")
    if(NOT arg_NO_CONFIG_POSTFIX)
      set_target_properties(${target} PROPERTIES DEV_POSTFIX -dev IREL_POSTFIX -irel DBG_POSTFIX -dbg)
    endif()
    if(arg_OUTPUT_DIR)
      _dagor_abs_paths(output_dir "${arg_OUTPUT_DIR}")
    else()
      set(output_dir "${CMAKE_BINARY_DIR}/bin")
    endif()
    # one dir for every configuration: the names differ by their postfix ($<1:> stops the per-config subdirs)
    set_target_properties(${target} PROPERTIES
      RUNTIME_OUTPUT_DIRECTORY "$<1:${output_dir}>"
      LIBRARY_OUTPUT_DIRECTORY "$<1:${output_dir}>"
      PDB_OUTPUT_DIRECTORY "$<1:${output_dir}>")
  endif()
  if(type MATCHES "^(EXECUTABLE|SHARED_LIBRARY|MODULE_LIBRARY)$")
    _dagor_build_stamp(stamp)
    target_link_libraries(${target} PRIVATE ${stamp})
  endif()
  if(type STREQUAL "EXECUTABLE" AND DAGOR_PLATFORM STREQUAL "windows" AND NOT arg_CONSOLE)
    set_property(TARGET ${target} PROPERTY WIN32_EXECUTABLE ON)
  endif()

  set_property(GLOBAL APPEND PROPERTY DAGOR_TARGETS "${target}")
endfunction()

# the object library with dagor_exe_build_date/_time (dagor_get_build_stamp_str), linked into every program
function(_dagor_build_stamp out)
  set(${out} dagor.buildStamp PARENT_SCOPE)
  if(TARGET dagor.buildStamp)
    return()
  endif()
  if(DAGOR_BUILD_STAMP)
    string(TIMESTAMP date "%b %d %Y")
    string(TIMESTAMP time "%H:%M:%S")
  else()
    set(date "*")
    set(time "*")
  endif()
  set(file "${CMAKE_BINARY_DIR}/dagor/buildStamp.c")
  file(CONFIGURE OUTPUT "${file}" CONTENT
    "const char *dagor_exe_build_date = \"${date}\";\nconst char *dagor_exe_build_time = \"${time}\";\n")
  add_library(dagor.buildStamp OBJECT "${file}")
  target_link_libraries(dagor.buildStamp PRIVATE Dagor::BuildSettings)
  target_include_directories(dagor.buildStamp BEFORE PRIVATE ${DAGOR_BASE_INCLUDES})
endfunction()

# the default name of a target declared in an engine directory: its path under prog/ with '/' as '.'
function(_dagor_target_name out first)
  if(first AND NOT first IN_LIST _DAGOR_TARGET_OPTIONS AND NOT first IN_LIST _DAGOR_TARGET_ONE_VALUE
     AND NOT first IN_LIST _DAGOR_TARGET_MULTI_VALUE AND NOT first MATCHES "^(STATIC|SHARED|OBJECT|INTERFACE)$")
    set(${out} "${first}" PARENT_SCOPE)
    set(${out}_GIVEN ON PARENT_SCOPE)
    return()
  endif()
  _dagor_base_dir(base)
  _dagor_dir_ref("${base}" ref)
  if(NOT ref)
    message(FATAL_ERROR "Targets outside the engine's prog/ need a name (${base})")
  endif()
  dagor_ref_target("${ref}" name)
  set(${out} "${name}" PARENT_SCOPE)
  set(${out}_GIVEN OFF PARENT_SCOPE)
endfunction()

# dagor_add_library([<name>] [STATIC|OBJECT|INTERFACE] [SOURCES ...] [SOURCE_DIRS <dir>... [GLOB <pattern>...]
#   [EXCLUDE <regex>...]] [PUBLIC_INCLUDES ...] [PRIVATE_INCLUDES ...] [PUBLIC_DEFINES ...] [PRIVATE_DEFINES ...]
#   [COMPILE_OPTIONS ...] [C_OPTIONS <options of the C sources>...] [PUBLIC_COMPILE_OPTIONS ...] [SOURCE_OPTIONS <file> <option>...] [DEPS <ref>...]
#   [PUBLIC_DEPS <ref>...] [SYSTEM_LIBS ...] [LINK_OPTIONS ...] [STRICT] [THIRD_PARTY] [EXCEPTIONS ON|OFF]
#   [QUIRREL] (Quirrel's headers and libraries) [QUIRREL_HEADERS] (its headers only)
#   [RTTI ON|OFF] [FORCE_INCLUDES <header>...] [PCH <header>] [NO_UNITY] [FOLDER <folder>] [LICENSE_FILES ...]
#   [PROPERTIES <property> <value>...] [STRINGIFY <file>...] [STRINGIFY_ARRAY <file>...] (see DagorCodegen.cmake)
# <name> defaults to the directory's path under prog/ with '/' as '.' (see dagor_ref_target).
function(dagor_add_library)
  _dagor_target_name(name "${ARGV0}")
  set(args ${ARGN})
  if(name_GIVEN)
    list(POP_FRONT args)
  endif()
  set(type STATIC)
  list(GET args 0 first)
  if(first MATCHES "^(STATIC|OBJECT|INTERFACE)$")
    set(type "${first}")
    list(POP_FRONT args)
  endif()
  add_library(${name} ${type})
  get_property(cmake_type TARGET ${name} PROPERTY TYPE)
  _dagor_setup_target(${name} ${cmake_type} ${args})
endfunction()

# dagor_add_shared_library(<name> ...): a DLL / shared object, with dagor_add_library's options and OUTPUT_DIR,
# OUTPUT_NAME, NO_CONFIG_POSTFIX
function(dagor_add_shared_library name)
  add_library(${name} SHARED)
  _dagor_setup_target(${name} SHARED_LIBRARY ${ARGN})
endfunction()

# dagor_add_executable(<name> [CONSOLE] [OUTPUT_DIR <dir>] [OUTPUT_NAME <name>] [NO_CONFIG_POSTFIX] ...): a program,
# with dagor_add_library's options. It is named <name>[-asan...][-cov]-<config>, without the config suffix in Rel, in
# OUTPUT_DIR (default <build>/bin). Without CONSOLE it is a GUI (/SUBSYSTEM:WINDOWS) program on Windows.
function(dagor_add_executable name)
  add_executable(${name})
  _dagor_setup_target(${name} EXECUTABLE ${ARGN})
endfunction()

# dagor_finalize(): the last call of the top-level CMakeLists.txt. It adds the engine directories the targets use
# (and every one with DAGOR_ADD_ALL), until no new ones are needed, then checks that every reference resolved.
function(dagor_finalize)
  if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    message(FATAL_ERROR "dagor_finalize() belongs at the end of the top-level CMakeLists.txt")
  endif()
  get_property(done GLOBAL PROPERTY DAGOR_FINALIZED)
  if(done)
    message(FATAL_ERROR "dagor_finalize() was called twice")
  endif()
  set_property(GLOBAL PROPERTY DAGOR_FINALIZED ON)

  if(DAGOR_ADD_ALL)
    file(GLOB_RECURSE lists RELATIVE "${DAGOR_PROG_DIR}" "${DAGOR_PROG_DIR}/*/CMakeLists.txt")
    foreach(list IN LISTS lists)
      file(STRINGS "${DAGOR_PROG_DIR}/${list}" uses REGEX "dagor_add_" LIMIT_COUNT 1)
      if(uses)
        cmake_path(GET list PARENT_PATH ref)
        _dagor_queue_dir("${ref}" "DAGOR_ADD_ALL")
      endif()
    endforeach()
  endif()

  get_property(pending GLOBAL PROPERTY DAGOR_PENDING_DIRS)
  while(pending)
    list(POP_FRONT pending ref)
    set_property(GLOBAL PROPERTY DAGOR_PENDING_DIRS "${pending}")
    if(NOT EXISTS "${DAGOR_PROG_DIR}/${ref}/CMakeLists.txt")
      get_property(requester GLOBAL PROPERTY DAGOR_DIR_${ref}_REQUESTER)
      message(FATAL_ERROR "${requester} uses prog/${ref}, which has no CMakeLists.txt")
    endif()
    add_subdirectory("${DAGOR_PROG_DIR}/${ref}" "${CMAKE_BINARY_DIR}/_e/${ref}")
    get_property(pending GLOBAL PROPERTY DAGOR_PENDING_DIRS)
  endwhile()

  get_property(required GLOBAL PROPERTY DAGOR_REQUIRED_TARGETS)
  list(REMOVE_DUPLICATES required)
  set(missing)
  foreach(name IN LISTS required)
    if(NOT TARGET ${name})
      get_property(users GLOBAL PROPERTY DAGOR_TARGET_${name}_USERS)
      list(REMOVE_DUPLICATES users)
      list(JOIN users ", " users)
      list(APPEND missing "  ${name} (used by ${users})")
    endif()
  endforeach()
  if(missing)
    list(JOIN missing "\n" missing)
    message(FATAL_ERROR "Library references to directories that declare no target of that name:\n${missing}")
  endif()
  dagor_check_system_libs()
endfunction()
