# Fetching of pinned archives (SDKs, toolchains) into the deps cache, usable before project() and from toolchain files.
#
# prog/cmake/sdk/manifest.cmake declares every archive with dagor_sdk(); dagor_fetch_sdk() downloads, verifies and unpacks
# it once into ${DAGOR_DEPS_DIR}/sdk/<name>-<version>[-<host>]. Each SDK can be replaced by a local copy with
# -DDAGOR_SDK_<NAME>_DIR=<dir> (the name upper-cased, '-' as '_'), which is also the way to build offline.
include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/DagorHost.cmake")

# dagor_sdk(<name> <version> <host-tag|any> URL <url> SHA256 <hash> [FILE <download file name>]
#           [EXTRACT <pattern>...] [<host-tag|any> ...])
# One entry per host the archive exists for: 'windows-x86_64', 'linux-arm64', ... or 'any' for host-independent ones.
# EXTRACT unpacks only the archive members matching the globs (relative to the archive root, the top dir included).
function(dagor_sdk name version)
  set(_hosts)
  set(_host)
  set(_key)
  foreach(arg IN LISTS ARGN)
    if(arg MATCHES "^(any|(windows|linux|macOS)-(x86_64|arm64|e2k))$" AND (NOT _key OR _key STREQUAL "EXTRACT"))
      set(_host "${arg}")
      set(_key)
      list(APPEND _hosts "${arg}")
    elseif(arg MATCHES "^(URL|SHA256|FILE|EXTRACT)$" AND (NOT _key OR _key STREQUAL "EXTRACT"))
      set(_key "${arg}")
    elseif(_key)
      if(NOT _host)
        message(FATAL_ERROR "dagor_sdk(${name}): ${_key} before a host tag")
      endif()
      if(_key STREQUAL "EXTRACT")
        set_property(GLOBAL APPEND PROPERTY DAGOR_SDK_${name}_${_host}_${_key} "${arg}")
      else()
        set_property(GLOBAL PROPERTY DAGOR_SDK_${name}_${_host}_${_key} "${arg}")
        set(_key)
      endif()
    else()
      message(FATAL_ERROR "dagor_sdk(${name}): unexpected '${arg}'")
    endif()
  endforeach()
  foreach(host IN LISTS _hosts)
    foreach(key URL SHA256)
      get_property(value GLOBAL PROPERTY DAGOR_SDK_${name}_${host}_${key})
      if(NOT value)
        message(FATAL_ERROR "dagor_sdk(${name}): no ${key} for ${host}")
      endif()
    endforeach()
  endforeach()
  set_property(GLOBAL PROPERTY DAGOR_SDK_${name}_VERSION "${version}")
  set_property(GLOBAL PROPERTY DAGOR_SDK_${name}_HOSTS "${_hosts}")
endfunction()

include("${CMAKE_CURRENT_LIST_DIR}/sdk/manifest.cmake")

# the DAGOR_SDK_<NAME>_DIR override variable of an SDK
function(_dagor_sdk_override_var name out)
  string(TOUPPER "${name}" upper)
  string(REPLACE "-" "_" upper "${upper}")
  set(${out} "DAGOR_SDK_${upper}_DIR" PARENT_SCOPE)
endfunction()

# dagor_sdk_version(<name> <out-var>): the pinned version of an SDK
function(dagor_sdk_version name out)
  get_property(version GLOBAL PROPERTY DAGOR_SDK_${name}_VERSION)
  if(NOT version)
    message(FATAL_ERROR "SDK '${name}' is not declared in prog/cmake/sdk/manifest.cmake")
  endif()
  set(${out} "${version}" PARENT_SCOPE)
endfunction()

# dagor_fetch_sdk(<name> <out-dir-var> [HOST <host-tag>] [OPTIONAL])
# Sets <out-dir-var> to the unpacked SDK dir; with OPTIONAL it is set to empty when the SDK has no archive for the host.
function(dagor_fetch_sdk name out)
  cmake_parse_arguments(PARSE_ARGV 2 arg "OPTIONAL" "HOST" "")
  _dagor_sdk_override_var("${name}" override)
  if(${override})
    if(NOT IS_DIRECTORY "${${override}}")
      message(FATAL_ERROR "${override}='${${override}}' is not a directory")
    endif()
    set(${out} "${${override}}" PARENT_SCOPE)
    return()
  endif()

  dagor_sdk_version("${name}" version)
  get_property(hosts GLOBAL PROPERTY DAGOR_SDK_${name}_HOSTS)
  if(NOT arg_HOST)
    set(arg_HOST "${DAGOR_HOST_TAG}")
  endif()
  if(arg_HOST IN_LIST hosts)
    set(host "${arg_HOST}")
    set(dir_suffix "-${host}")
  elseif("any" IN_LIST hosts)
    set(host any)
    set(dir_suffix "")
  elseif(arg_OPTIONAL)
    set(${out} "" PARENT_SCOPE)
    return()
  else()
    message(FATAL_ERROR "SDK '${name}' ${version} has no archive for ${arg_HOST}; point ${override} at a local copy")
  endif()

  get_property(url GLOBAL PROPERTY DAGOR_SDK_${name}_${host}_URL)
  get_property(sha256 GLOBAL PROPERTY DAGOR_SDK_${name}_${host}_SHA256)
  get_property(file GLOBAL PROPERTY DAGOR_SDK_${name}_${host}_FILE)
  get_property(extract GLOBAL PROPERTY DAGOR_SDK_${name}_${host}_EXTRACT)
  set(identity "${sha256} ${extract}") # what the stamp of an unpacked SDK records
  if(NOT file)
    cmake_path(GET url FILENAME file)
  endif()

  if(NOT DAGOR_DEPS_DIR)
    message(FATAL_ERROR "DAGOR_DEPS_DIR is not set; include DagorBootstrap.cmake first")
  endif()
  set(dest "${DAGOR_DEPS_DIR}/sdk/${name}-${version}${dir_suffix}")
  set(stamp "${dest}/.dagor-sdk")
  if(EXISTS "${stamp}")
    file(READ "${stamp}" stamped)
    if(stamped STREQUAL identity)
      set(${out} "${dest}" PARENT_SCOPE)
      return()
    endif()
  endif()

  # one configure at a time fetches a given SDK; the others wait and then find it unpacked
  file(MAKE_DIRECTORY "${DAGOR_DEPS_DIR}/sdk" "${DAGOR_DEPS_DIR}/downloads")
  file(LOCK "${dest}.lock" GUARD FUNCTION TIMEOUT 7200 RESULT_VARIABLE lock_result)
  if(lock_result)
    message(FATAL_ERROR "Cannot lock ${dest}.lock: ${lock_result}")
  endif()
  if(EXISTS "${stamp}")
    file(READ "${stamp}" stamped)
    if(stamped STREQUAL identity)
      set(${out} "${dest}" PARENT_SCOPE)
      return()
    endif()
  endif()

  set(archive "${DAGOR_DEPS_DIR}/downloads/${file}")
  if(EXISTS "${archive}")
    file(SHA256 "${archive}" have)
    if(NOT have STREQUAL sha256)
      file(REMOVE "${archive}")
    endif()
  endif()
  if(NOT EXISTS "${archive}")
    message(STATUS "Downloading ${name} ${version}: ${url}")
    file(DOWNLOAD "${url}" "${archive}.part" EXPECTED_HASH SHA256=${sha256} TLS_VERIFY ON SHOW_PROGRESS
         INACTIVITY_TIMEOUT 120 STATUS status)
    list(GET status 0 code)
    if(NOT code EQUAL 0)
      file(REMOVE "${archive}.part")
      list(GET status 1 error)
      message(FATAL_ERROR "Downloading ${url} failed: ${error}")
    endif()
    file(RENAME "${archive}.part" "${archive}")
  endif()

  message(STATUS "Unpacking ${name} ${version} to ${dest}")
  file(REMOVE_RECURSE "${dest}" "${dest}.tmp")
  if(file MATCHES "\\.(zip|nupkg|tar|tar\\.gz|tgz|tar\\.xz|txz|tar\\.bz2|7z)$")
    if(extract)
      file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${dest}.tmp" PATTERNS ${extract})
    else()
      file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${dest}.tmp")
    endif()
    # an archive of a single top-level dir is unpacked without it
    file(GLOB top LIST_DIRECTORIES true "${dest}.tmp/*")
    list(LENGTH top count)
    if(count EQUAL 1 AND IS_DIRECTORY "${top}")
      file(RENAME "${top}" "${dest}")
      file(REMOVE_RECURSE "${dest}.tmp")
    else()
      file(RENAME "${dest}.tmp" "${dest}")
    endif()
  else()
    file(MAKE_DIRECTORY "${dest}")
    file(COPY_FILE "${archive}" "${dest}/${file}")
  endif()
  file(WRITE "${stamp}" "${identity}")
  file(REMOVE "${archive}") # the unpacked SDK is what is kept (and what CI caches)
  set(${out} "${dest}" PARENT_SCOPE)
endfunction()
