# Microsoft DirectX Shader Compiler (dxcompiler and dxil), which the shader compilers load at run time: sdk::dxc with
# its headers (<dxc/dxcapi.h>), DAGOR_SDK_DXC_RUNTIME (the libraries to put next to them, for the target arch) and
# DAGOR_SDK_DXC_LICENSES.
dagor_fetch_sdk(dxc _dagor_dxc_dir)
set(DAGOR_SDK_DXC_ROOT "${_dagor_dxc_dir}")
if(DAGOR_PLATFORM STREQUAL "windows")
  # the Windows release has its headers in inc/; the code includes them as <dxc/...>
  if(NOT EXISTS "${_dagor_dxc_dir}/include/dxc/dxcapi.h")
    file(COPY "${_dagor_dxc_dir}/inc/" DESTINATION "${_dagor_dxc_dir}/include/dxc")
  endif()
  if(DAGOR_ARCH STREQUAL "x86_64")
    set(_dagor_dxc_bin "${_dagor_dxc_dir}/bin/x64")
  else()
    set(_dagor_dxc_bin "${_dagor_dxc_dir}/bin/arm64")
  endif()
  set(_dagor_dxc_runtime "${_dagor_dxc_bin}/dxcompiler.dll" "${_dagor_dxc_bin}/dxil.dll")
  file(GLOB _dagor_dxc_licenses "${_dagor_dxc_dir}/LICENSE-*.txt")
elseif(DAGOR_PLATFORM STREQUAL "linux")
  set(_dagor_dxc_runtime "${_dagor_dxc_dir}/lib/libdxcompiler.so" "${_dagor_dxc_dir}/lib/libdxil.so")
  file(GLOB _dagor_dxc_licenses "${_dagor_dxc_dir}/LICENSE-*.txt")
elseif(DAGOR_PLATFORM STREQUAL "macOS")
  set(_dagor_dxc_runtime "${_dagor_dxc_dir}/lib/macosx/dxcompiler.dylib" "${_dagor_dxc_dir}/lib/macosx/dxil.dylib")
  set(_dagor_dxc_licenses "${_dagor_dxc_dir}/LICENSE.TXT")
else()
  message(FATAL_ERROR "No DXC for ${DAGOR_PLATFORM}")
endif()
# cached: the module runs once per configure, the variables are read in other scopes
set(DAGOR_SDK_DXC_RUNTIME "${_dagor_dxc_runtime}" CACHE INTERNAL "")
set(DAGOR_SDK_DXC_LICENSES "${_dagor_dxc_licenses}" CACHE INTERNAL "")
foreach(_dagor_file IN LISTS DAGOR_SDK_DXC_RUNTIME)
  if(NOT EXISTS "${_dagor_file}")
    message(FATAL_ERROR "The DXC SDK in '${_dagor_dxc_dir}' has no ${_dagor_file}")
  endif()
endforeach()
add_library(sdk::dxc INTERFACE IMPORTED GLOBAL)
set_target_properties(sdk::dxc PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_dagor_dxc_dir}/include")
unset(_dagor_dxc_dir)
unset(_dagor_dxc_bin)
unset(_dagor_file)
unset(_dagor_dxc_runtime)
unset(_dagor_dxc_licenses)
