# Oodle (RAD Game Tools), user-provided: it cannot be redistributed. -DDAGOR_SDK_OODLE_DIR=<the unpacked Oodle 2 SDK>
# (the dir with include/ and lib/ or static_lib/) builds its codecs into engine/ioSys; without it they are stubs.
# Sets DAGOR_SDK_OODLE_ROOT and the imported target sdk::oodle.
set(DAGOR_SDK_OODLE_DIR "" CACHE PATH "Oodle 2 SDK (optional, not redistributable)")
set(DAGOR_SDK_OODLE_ROOT "")
if(DAGOR_SDK_OODLE_DIR)
  if(NOT EXISTS "${DAGOR_SDK_OODLE_DIR}/include/oodle2.h")
    message(FATAL_ERROR "DAGOR_SDK_OODLE_DIR='${DAGOR_SDK_OODLE_DIR}' has no include/oodle2.h")
  endif()
  if(DAGOR_PLATFORM STREQUAL "windows")
    if(DAGOR_ARCH STREQUAL "x86_64")
      set(_dagor_oodle_lib static_lib/oo2core_win64.lib)
    else()
      set(_dagor_oodle_lib static_lib/oo2core_winuwparm64.lib)
    endif()
  elseif(DAGOR_PLATFORM STREQUAL "macOS")
    set(_dagor_oodle_lib lib/liboo2coremac64.a)
  elseif(DAGOR_PLATFORM STREQUAL "linux")
    set(_dagor_oodle_lib lib/liboo2corelinux64.a)
  elseif(DAGOR_PLATFORM STREQUAL "android")
    set(_dagor_oodle_lib lib/android/arm64-v8a/liboo2coreandroid.a)
  elseif(DAGOR_PLATFORM STREQUAL "iOS")
    set(_dagor_oodle_lib lib/ios/liboo2coreios.a)
  endif()
  if(NOT _dagor_oodle_lib OR NOT EXISTS "${DAGOR_SDK_OODLE_DIR}/${_dagor_oodle_lib}")
    message(FATAL_ERROR "The Oodle SDK in '${DAGOR_SDK_OODLE_DIR}' has no library for ${DAGOR_TARGET_TAG} (${_dagor_oodle_lib})")
  endif()
  add_library(sdk::oodle STATIC IMPORTED GLOBAL)
  set_target_properties(sdk::oodle PROPERTIES IMPORTED_LOCATION "${DAGOR_SDK_OODLE_DIR}/${_dagor_oodle_lib}")
  set(DAGOR_SDK_OODLE_ROOT "${DAGOR_SDK_OODLE_DIR}")
  unset(_dagor_oodle_lib)
elseif(NOT DAGOR_SDK_OPTIONAL)
  message(FATAL_ERROR "The Oodle SDK is required: set DAGOR_SDK_OODLE_DIR")
endif()
